sudo: required
service:
  - docker

before_install:
  - docker build -t ducchibui/reactci -f Dockerfile.dev .

script:
  - docker run -e CI=true ducchibui/reactci npm run test

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: Reactci
    env: "Reactci-env"
